path_dataset: '/teamspace/studios/this_studio/datasets'
path_instructions: '/teamspace/studios/this_studio/letsdoit/instructions/sample_instructions.json'
data_asset_type: 'wide'
data_split: 'dev'
loader_sample_freq: 1
retriever_topk: 10
retriever_max_similarity_thresh: 0.97
finder_box_threshold: 0.3
finder_text_threshold: 0.25
merger_dist_thresh: 0.1
merger_geo_similarity_thresh: 0.7
merger_feat_similarity_thresh: 0.7
merger_n_points: 1000
path_submission_folder: '/teamspace/studios/this_studio/submission_opensun3d_track2'